#!/usr/bin/env python3
"""详细分析3个失败测试的原因"""

print("=" * 80)
print("3个失败测试的详细分析")
print("=" * 80)

print("\n1. HumanEval_151_double_the_difference")
print("-" * 80)
print("问题: isinstance 类型判断错误")
print("错误: AssertionError: candidate([5.0, 4.0]) == 25")
print()
print("生成的代码:")
print("  isinstance(x, int) and x > 0 and x % 2 != 0")
print()
print("根本原因:")
print("  ❌ isinstance(x, int) 会过滤掉 5.0 (float 类型)")
print("  ✅ 应该用: x == int(x) 或 isinstance(x, (int, float)) and x == int(x)")
print()
print("工具行为:")
print("  - 10轮重试")
print("  - 只使用2个工具: assemblesnippets, assemblesnippets12")
print("  - 每轮生成完全相同的错误代码")
print("  - 工具完全没有学习或改进")
print()
print("失败模式: 🔄 工具重复 + ❌ 逻辑错误不修正")
print()

print("\n2. HumanEval_160_do_algebra")
print("-" * 80)
print("问题: 工具导入限制")
print("错误: AssertionError: candidate(['+', '*', '-'], [2, 3, 4, 5]) == 9")
print()
print("工具调用:")
print("  - generatemath6, 18, 30, 42, 54")
print("  - 所有工具都返回: ImportError: Import blocked: decimal")
print()
print("根本原因:")
print("  ❌ 所有 generatemath 系列工具都尝试导入 decimal 模块")
print("  ❌ decimal 模块被安全沙箱阻止")
print("  ❌ 5轮重试都选择相同类型的工具（generatemath 系列）")
print()
print("工具行为:")
print("  - 5轮重试")
print("  - 使用5个不同工具，但都是 generatemath 系列")
print("  - 所有工具都有相同的导入限制问题")
print("  - LLM 没有意识到应该切换到其他类型的工具")
print()
print("失败模式: 🚫 系统限制 + 🔁 工具类型单一")
print()

print("\n3. HumanEval_105_by_length")
print("-" * 80)
print("问题: 参数名错误")
print("错误: NameError: name 'lst' is not defined. Did you mean: 'list'?")
print()
print("函数签名: by_length(arr: List[int])")
print("生成的代码: if not lst:")
print()
print("根本原因:")
print("  ❌ 函数参数名是 'arr'，但代码中使用了 'lst'")
print("  ❌ LLM 没有遵守约束 '必须使用函数签名中的实际参数名'")
print()
print("工具行为:")
print("  - 使用 planner 角色（而非 builder）")
print("  - 3个工具: planrisk13, planarchitecture15, plantimebox14")
print("  - Planner 工具不生成可执行代码，只生成规划")
print("  - 最终使用 llm_fallback 提取代码，但提取失败")
print()
print("失败模式: 🎭 角色选择错误 + 📝 参数名不匹配")
print()

print("\n" + "=" * 80)
print("失败原因总结")
print("=" * 80)

print("\n失败类型分布:")
print("  1. 逻辑错误 + 工具重复无学习:     HumanEval_151")
print("  2. 系统限制 + 工具类型选择单一:    HumanEval_160")
print("  3. 角色错误 + 参数名不匹配:        HumanEval_105")
print()

print("共性问题:")
print("  ✅ 错误信息已记录")
print("  ❌ 工具没有有效利用错误信息改进")
print("  ❌ 工具选择策略缺乏多样性")
print("  ❌ 角色路由有时不正确（planner vs builder）")
print()

print("改进建议优先级:")
print()
print("🔥 P0 - 立即修复:")
print("  1. HumanEval_151: 在提示词中明确指出 isinstance 问题")
print("     添加: '对于浮点数如5.0，不要用isinstance(x, int)，应该用 x == int(x)'")
print()
print("  2. HumanEval_105: 强化参数名约束")
print("     添加: '代码必须使用参数名 arr，不要用 lst/data/items 等'")
print()
print("⚡ P1 - 工具策略:")
print("  3. 工具多样性: 失败3次后强制切换到不同类别的工具")
print("     当前: assemblesnippets -> assemblesnippets12 (同类)")
print("     改进: assemblesnippets -> generateedgecase -> generatefunctionbody (不同类)")
print()
print("  4. 系统限制检测: ImportError 时立即切换工具类型")
print("     当前: generatemath6 -> generatemath18 -> generatemath30 (同类)")
print("     改进: generatemath6 失败 -> assemblesnippets (不同类)")
print()
print("🔧 P2 - 角色路由:")
print("  5. 对于 builder 任务，避免路由到 planner")
print("  6. 检查 llm_fallback 的代码提取逻辑")
